name: Update README

on:
  schedule:
    - cron: "0 0 * * *"  # Chạy hàng ngày vào 00:00 UTC
  workflow_dispatch: 

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate GitHub Stats
        uses: anuraghazra/github-readme-stats@master
        with:
          username: DQP-UIT

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.md
          git commit -m "Updated README with latest stats" || exit 0
          git push
