name: Update GitHub Profile README

on:
  schedule:
    - cron: "0 0 1 */3 *" # Chạy vào 00:00 ngày 1 của mỗi 3 tháng (Tháng 1, 4, 7, 10)
  workflow_dispatch: # Cho phép chạy thủ công nếu cần

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate GitHub Stats Image
        run: |
          curl -o github-stats.svg "https://github-readme-stats.vercel.app/api?username=DQP-UIT&show_icons=true&theme=radical"
          curl -o github-top-langs.svg "https://github-readme-stats.vercel.app/api/top-langs/?username=DQP-UIT&layout=compact"
          curl -o github-trophies.svg "https://github-profile-trophy.vercel.app/?username=DQP-UIT&theme=darkhub"

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Updated GitHub Stats in README"
          git push
